# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

class TestPruebafuncional():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_pruebafuncional(self):
        for i in range(100):
            try:
                print(f"Ingreso número {i + 1}")

                # Abrir la página de login
                self.driver.get("http://localhost/login-signup-2022/login.php")
                self.driver.set_window_size(1936, 1056)
                time.sleep(2)  # Esperar a que cargue la página

                # Ingresar credenciales
                self.driver.find_element(By.NAME, "uname").send_keys("JJ")
                self.driver.find_element(By.NAME, "pass").send_keys("12345")
                self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
                time.sleep(2)  # Esperar después de iniciar sesión

                # Cerrar sesión si existe el botón de logout
                logout_btn = self.driver.find_element(By.LINK_TEXT, "Logout")
                if logout_btn:
                    logout_btn.click()
                    time.sleep(2)  # Esperar después del logout

            except Exception as e:
                print(f"Error en el intento {i + 1}: {e}")

        print("Automatización completada.")

if __name__ == "__main__":
    prueba = TestPruebafuncional()
    prueba.setup_method(None)
    prueba.test_pruebafuncional()
    prueba.teardown_method(None)
